### ISSUE TITLE
Database Is missing

### ISSUE THREAD

**Issue by yasser77** [sarwat33/digitalmyschool#1]
Hey can u please upload the .sql file
and also the log info for this demo 
http://digitalmyschool.epizy.com/index.php 

thank you

**Comment by bear-aka47** [comment]
Hello , if you are trying to log in then use 
Username : admin1
Password : admin1
But can't provide the database file currently

**Comment by sarwat33** [comment]
Hello , 
If you are trying to access the admin page for demo then use 
Username: admin1
Password: admin1

I can't provide you the database files as it's running currently on the server 
But you can use the admin page 
Thanks.
